ManagerHotel/WebClients/Controllers/AccommodationsController.cs
using DataBase.Data;
using DataBase.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebClients.Models;
using static WebClients.Models.FilterSortPagingApp;
using static WebClients.Models.AccommodationModel;
using System.Globalization;
using System.Data;
using DinkToPdf.Contracts;
using DinkToPdf;
using WebClients.TagHelpers;
using System.Text;

namespace WebClients.Controllers
{
    public class AccommodationsController : Controller
    {
        private ApplicationDbContext _context;
        private IConverter _converter;

        public IConfiguration Configuration;
        IWebHostEnvironment webHostEnvironment;
        
        public AccommodationsController(ApplicationDbContext context, IConverter converter, IConfiguration configuration, IWebHostEnvironment environment)
        {
            _converter = converter;
            _context = context;
            Configuration = configuration;
            webHostEnvironment = environment;
        }

        public async Task<IActionResult> RoomsIndex(int Id, SearchModel model, DateOnly DateOfArrival, DateOnly DepartureDate, int page = 1)
        {
            DateOnly someDate = new DateOnly(0001, 1, 1);
            int pageSize = 6;

            if (model.DateOfArrival == someDate)
            {
                model.DateOfArrival = DateOnly.FromDateTime(DateTime.Now);
            }

            if (model.DepartureDate == someDate)
            {
                model.DepartureDate = DateOnly.FromDateTime(DateTime.Now).AddDays(1);
            }

            if (model.CountPeople == 0)
            {
                model.CountPeople = 1;
            }
            if (DateOfArrival != someDate)
            {
                model.DateOfArrival = DateOfArrival;

            }
            if (DepartureDate != someDate)
            {
                model.DepartureDate = DepartureDate;
            }

            DateTime date1 = new DateTime(model.DateOfArrival.Year, model.DateOfArrival.Month, model.DateOfArrival.Day, 0, 0, 0);
            DateTime date2 = new DateTime(model.DepartureDate.Year, model.DepartureDate.Month, model.DepartureDate.Day, 0, 0, 0);

            IQueryable<RoomsCategory> _roomsCategory = _context.RoomsCategory.Where(x => x.MaxNumberOfPeople >= model.CountPeople + model.CountChildren && x.MinNumberOfPeople <= model.CountPeople + model.CountChildren);
            IQueryable<Rooms> _rooms = _context.Rooms.FromSqlRaw(@$"SELECT * FROM Rooms WHERE NOT EXISTS (SELECT * FROM Employment WHERE Employment.RoomId = Rooms.RoomOnTheFloor and Employment.StatusId != 2 and
            '{date1.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}' <= Employment.DateOfArrival and ('{date2.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}' != Employment.DepartureDate or
            '{date2.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}'<= Employment.DepartureDate))")
            .Include(x => x.RoomsCategory).Where(p => p.RoomsCategory.MaxNumberOfPeople >= model.CountPeople + model.CountChildren && p.RoomsCategory.MinNumberOfPeople <= model.CountPeople + model.CountChildren);

            IQueryable<RoomPrice> _price = _context.RoomPrice.Include(x => x.RoomsCategory).Where(x => date1 >= x.DateStartOfPeriod && date1 <= x.DateEndOfPeriod);

            //Сортировка по цене
            switch (model.Cost)
            {
                case 0:
                    _rooms = _rooms;
                    break;
                case 1:
                    _rooms = _context.Rooms.FromSqlRaw(@$"SELECT * FROM Rooms Full JOIN
                    RoomsCategory on Rooms.CategoryId =RoomsCategory.Id
                    Full JOIN RoomPrice on RoomPrice.IdCategory = RoomsCategory.Id
                    WHERE '{date1.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}' >= RoomPrice.DateStartOfPeriod and
                    '{date1.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}' <= RoomPrice.DateEndOfPeriod and
                    NOT EXISTS (SELECT * FROM Employment WHERE Employment.RoomId = Rooms.RoomOnTheFloor and Employment.StatusId != 2 and
                    '{date1.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}' <= Employment.DateOfArrival and ('{date2.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}' != Employment.DepartureDate or
                    '{date2.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}'<= Employment.DepartureDate))
                    ORDER BY MainPrice OFFSET 0 ROWS")
                    .Include(x => x.RoomsCategory).Where(p => p.RoomsCategory.MaxNumberOfPeople >= model.CountPeople + model.CountChildren);
                    break;
                case 2:
                    _rooms = _context.Rooms.FromSqlRaw(@$"SELECT * FROM Rooms Full JOIN
                    RoomsCategory on Rooms.CategoryId =RoomsCategory.Id
                    Full JOIN RoomPrice on RoomPrice.IdCategory = RoomsCategory.Id
                    WHERE '{date1.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}' >= RoomPrice.DateStartOfPeriod and
                    '{date1.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}' <= RoomPrice.DateEndOfPeriod and
                    NOT EXISTS (SELECT * FROM Employment WHERE Employment.RoomId = Rooms.RoomOnTheFloor and Employment.StatusId != 2 and
                    '{date1.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}' <= Employment.DateOfArrival and ('{date2.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}' != Employment.DepartureDate or
                    '{date2.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}' <= Employment.DepartureDate))
                    ORDER BY MainPrice DESC OFFSET 0 ROWS")
                    .Include(x => x.RoomsCategory).Where(p => p.RoomsCategory.MaxNumberOfPeople >= model.CountPeople + model.CountChildren);
                    break;
            }

            // Фильтрация по категории
            if (Id != 0)
            {
                _rooms = _rooms.Where(p => p.CategoryId == Id);
            }

            // Пагинация
            var Kolvo = await _rooms.CountAsync();
            var rooms = await _rooms.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            IndexModel viewModel = new IndexModel
            {
                Room = rooms,
                PageViewModel = new PageViewModel(Kolvo, page, pageSize),
                FilterViewModel = new FilterViewModel(_roomsCategory.ToList(), Id),
                RoomPrice = _price,
            };

            SearchModel view = new SearchModel
            {
                DateOfArrival = model.DateOfArrival,
                DepartureDate = model.DepartureDate,
                CountPeople = model.CountPeople,
                CountChildren = model.CountChildren,
                Cost = model.Cost,
                indexModel = viewModel
            };
            return View(view);
        }

        public async Task<IActionResult> Details(int RoomOnTheFloor, SearchModel m, string Return)
        {
            DateTime date1 = new DateTime(m.DateOfArrival.Year, m.DateOfArrival.Month, m.DateOfArrival.Day, 0, 0, 0);
            DateTime date2 = new DateTime(m.DepartureDate.Year, m.DepartureDate.Month, m.DepartureDate.Day, 0, 0, 0);

            if (RoomOnTheFloor != 0)
            {
                Rooms _room = await _context.Rooms.Include(x => x.RoomsCategory).FirstOrDefaultAsync(p => p.RoomOnTheFloor == RoomOnTheFloor);
                RoomPrice _price = await _context.RoomPrice.Include(x => x.RoomsCategory).Where(x => date1 >= x.DateStartOfPeriod && date1 <= x.DateEndOfPeriod).FirstOrDefaultAsync(p => p.IdCategory == _room.CategoryId);
                IEnumerable<Images> _images = await _context.Images.Where(x => x.RoomId == _room.RoomOnTheFloor).ToListAsync();
                
                //если пытаются забронировать занятый номер
                if (Return == "Yes")
                {
                    SearchModel view = new SearchModel
                    {
                        DateOfArrival = m.DateOfArrival,
                        DepartureDate = m.DepartureDate,
                        CountPeople = m.CountPeople,
                        CountChildren = m.CountChildren,
                    };
                    RoomsModel viewModel = new RoomsModel
                    {
                        Room = _room,
                        RoomPrice = _price,
                        Images = _images,
                        SearchModel = view,
                        Return = Return
                    };
                    return View(viewModel);
                }
                else
                {
                    SearchModel view = new SearchModel
                    {
                        DateOfArrival = m.DateOfArrival,
                        DepartureDate = m.DepartureDate,
                        CountPeople = m.CountPeople,
                        CountChildren = m.CountChildren,
                    };
                    RoomsModel viewModel = new RoomsModel
                    {
                        Room = _room,
                        RoomPrice = _price,
                        Images = _images,
                        SearchModel = view
                    };
                    return View(viewModel);
                }
            }
            return NotFound();
        }


        public async Task<IActionResult> Prepayment(int RoomOnTheFloor, SearchModel model, int? Price, string Pay)
        {
            if (RoomOnTheFloor != 0)
            {
                Rooms _room = await _context.Rooms.Include(x => x.RoomsCategory).FirstOrDefaultAsync(p => p.RoomOnTheFloor == RoomOnTheFloor);
                int days = 0;
                Users _user = await _context.Users.FirstOrDefaultAsync(p => p.Email == User.Identity.Name);
                RoomPrice _price = null;
                int TotalCost = 0;
                int prepayment = 0;

ManagerHotel/WebClients/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>@ViewData["Title"] ~ Mairi Hotel ~ </title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebClients.styles.css" asp-append-version="true" />
    <link rel="shortcut icon" type="images/x-icon" href="/2304834.jpg">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.7.1/jquery.min.js" integrity="sha512-BkBgWiL0N/EFIbLZYGTgbksKG5bS6PtwnWvVk3gccv+KhtK/4wkLxCRGh+kelKiXx7Ey4jfTabLg3AEIPC7ENA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css"/>
    
    <link rel="stylesheet" href="~/css/Animate.css">
    <link rel="stylesheet" href="~/css/Slider.css">
    <link rel="stylesheet" href="~/css/Boom.css">
    <link rel="stylesheet" href="~/css/icomoon.css">
    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/css/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="~/css/Dates.css">

    <script src="~/css/Scripts/query.min.js"></script>
    <script src="~/css/Scripts/query.waypoints.min.js"></script>
    <script src="~/css/Scripts/query.slider.js"></script>
    <script src="~/css/Scripts/bootstrap.min.js"></script>
    <script src="~/css/Scripts/Main.js"></script>
    <script src="~/css/Scripts/Date.js"></script>
   
    @await RenderSectionAsync("Scripts", required: false)

</head>
<body>
    <header>
       
        <nav class="colorlib-nav" role="navigation"> 
            <div class="top-menu">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-2">
                               <img style="height:50px;" src="/images/site/logotip.jpg" alt=" ">
                        </div>
                        <div class="col-xs-10 text-right menu-1">
                            <ul>
                                <li><a href="@Url.Action("Index", "Home")">Главная</a></li> 
                                <li><a href="@Url.Action("About", "Home")">О нас</a> </li> 
                                <li><a href="@Url.Action("SpecialOffers", "Home")">Спецпредложения</a> </li>
                                <li><a href="@Url.Action("RoomsIndex", "Accommodations")">Номера</a></li>
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <li><a href="@Url.Action("Login", "Account")">Авторизация</a></li>
                                    <li><a href="@Url.Action("Register", "Account")">Регистрация</a></li>
                                }
                                else
                                {
                                    <li><a href="@Url.Action("PersonalAccount", "Account")">Личный кабинет</a></li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
            @RenderBody()
            <footer id="colorlib-footer" role="contentinfo">
                <div class="container">
                  <div class="row row-pb-md">
                      <div class="col-md-3 colorlib-widget">
                      <h4>Быстрые ссылки</h4>
                      <p>
                        <ul class="colorlib-footer-links">
                            <li><a href="@Url.Action("Index", "Home")">Главная</a></li>
                            <li><a href="@Url.Action("About", "Home")">О нас</a> </li>
                            <li><a href="@Url.Action("SpecialOffers", "Home")">Спецпредложения</a> </li>
                            <li><a href="@Url.Action("RoomsIndex", "Accommodations")">Номера</a></li>
                            <li><a href="/document/Правила проживания.pdf" target="_ blank">Правила проживания</a></li>
                                </ul>
                        </p>
                    </div>
                <div class="col-md-5">
                    <h4>Новости</h4>
                     <ul class="colorlib-footer-links">
                        <li>Теперь в нашем отеле доступны услуги SPA и массажа. Для вас - разнообразные обертывания, косметология и разнообразный массаж.</li>
                        <li>Приглашаем вас отметить День Рождения в Mairi Hotel. Для вас мы предлагаем лучшие условия сервиса и уникальную атмосферу всесезонного природного курорта.</li>
                        <li>Для вас мы подготовили массу ежедневных активностей на каждый день.</li>
                     </ul>
                     </div>
                        <div class="col-md-3 col-md-push-1">
                            <h4>Контакты</h4>
                            <ul class="colorlib-footer-links">
                        <li><i class="icon-map-pin"></i> Карачаево-Черкесская Республика,Архыз, поселок Романтик,ул. Горная, 13.</li>
                        <li><i class="icon-phone3"></i> +7-991-131-53-91</li>
                        <li><i class="icon-chat"></i> www.mairihotel.com</li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <p>
                                <small class="block">"Mairi Hotel" © 2024 Официальный сайт гостиницы  |  Managed by UPRO</small>
                            </p>
                        </div>
                    </div>
                </div>
            </footer>
</body>
</html>